### ISSUE TITLE
Izin clone

### ISSUE THREAD

**Issue by lian2901** [castrix/fit-vue3-boilerplate#1]
Izin clone mas

**Comment by castrix** [comment]
Oke mas, silahkan

**Comment by lian2901** [comment]
thanks ya mas. Maaf mas kalo saya masih ngawang dan masih liat2 kodingan mas

Pada tanggal Rab, 10 Nov 2021 pukul 14.02 Ihsan Fajar Ramadhan <
***@***.***> menulis:
